spring.application.name=levecare-patients
spring.main.banner-mode=off

# Structured JSON logs for CloudWatch (ECS format)
logging.structured.format.console=ecs

app.table-name=${TABLE_NAME:levecare-patients}
app.event-bus-name=${EVENT_BUS_NAME:levecare-bus}
